language: go

go:
    - 1.8

install: go get -v github.com/spf13/hugo # Install latest and greatest Hugo -for the brave

script:
    - cd sabbatical-hugo # Our sources live here
    -  hugo              # Hugo will default to writing output to public, theme is configured in config

deploy:
  provider: pages        # The Github pages provider
  skip_cleanup: true     # Do not remove the output files of our builds, as we need to deploy them
  local_dir: public      # Github outpus to here
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
